# Generated by Django 5.2.7 on 2025-12-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='year_of_release',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
